---
name: "package-miyamoto-patch"

on:
  push:
    paths:
      - "MiyamotoPatch/Tsuru/**"

jobs:
  auto-release:
    name: "Automatic Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Pack"
        run: |
          sudo apt install -y zip
          zip -r TsuruMiyamotoPatch.zip . -i MiyamotoPatch/Tsuru/**

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest Miyamoto Patch"
          files: |
            TsuruMiyamotoPatch.zip
